apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: average-sessions-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: average-sessions-v1
        version: v1
    spec:
      containers:
      - name: average-sessions
        image: pull gcr.io/bigtable-sessionize/github-chengke-gcp-bigtable-sessionize/average-sessions
        imagePullPolicy: IfNotPresent
        resources: 
          requests: 
            cpu: "125m"
            memory: "64Mi"
        volumeMounts:
        - name: credentials
          mountPath: "/credentials"
          readOnly: true
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/average-sessions.json
      volumes:
      - name: credentials
        secret:
          secretName: average-sessions-credential
